export type GalleryImg = { src: string; label: string; span: number };

export const GALLERY_IMGS: GalleryImg[] = [
  { src: "/assets/img/images/Villa_Istria.webp", label: "Villa exterior", span: 1 },
  { src: "/assets/img/images/Villa_Istria-2.webp", label: "Exterior", span: 1 },
  { src: "/assets/img/images/Villa_Istria-3.webp", label: "Exterior", span: 1 },
  { src: "/assets/img/images/Villa_Istria-4.webp", label: "Exterior", span: 1 },
  { src: "/assets/img/images/Villa_Istria-5.webp", label: "Pool area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-6.webp", label: "Pool area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-7.webp", label: "Garden", span: 1 },
  { src: "/assets/img/images/Villa_Istria-8.webp", label: "Garden", span: 2 },
  { src: "/assets/img/images/Villa_Istria-9.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-10.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-11.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-12.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-13.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-14.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-15.webp", label: "Kitchen & dining", span: 1 },
  { src: "/assets/img/images/Villa_Istria-16.webp", label: "Interior", span: 1 },
  { src: "/assets/img/images/Villa_Istria-17.webp", label: "Interior", span: 1 },
  { src: "/assets/img/images/Villa_Istria-18.webp", label: "Interior", span: 1 },
  { src: "/assets/img/images/Villa_Istria-19.webp", label: "Interior", span: 1 },
  { src: "/assets/img/images/Villa_Istria-20.webp", label: "Living room", span: 1 },
  { src: "/assets/img/images/Villa_Istria-21.webp", label: "Living room", span: 1 },
  { src: "/assets/img/images/Villa_Istria-22.webp", label: "Bedroom — pool access", span: 1 },
  { src: "/assets/img/images/Villa_Istria-24.webp", label: "Bedroom", span: 1 },
  { src: "/assets/img/images/Villa_Istria-25.webp", label: "Bedroom — sea view", span: 1 },
  { src: "/assets/img/images/Villa_Istria-26.webp", label: "Bedroom", span: 1 },
  { src: "/assets/img/images/Villa_Istria-27.webp", label: "Bedroom", span: 1 },
  { src: "/assets/img/images/Villa_Istria-28.webp", label: "Bedroom detail", span: 1 },
  { src: "/assets/img/images/Villa_Istria-29.webp", label: "Bedroom detail", span: 1 },
  { src: "/assets/img/images/Villa_Istria-30.webp", label: "Bathroom", span: 1 },
  { src: "/assets/img/images/Villa_Istria-31.webp", label: "Bathroom", span: 1 },
  { src: "/assets/img/images/Villa_Istria-32.webp", label: "Bathroom", span: 1 },
  { src: "/assets/img/images/Villa_Istria-33.webp", label: "Interior detail", span: 1 },
  { src: "/assets/img/images/Villa_Istria-34.webp", label: "Swimming pool", span: 1 },
  { src: "/assets/img/images/Villa_Istria-35.webp", label: "Pool area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-36.webp", label: "Pool area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-37.webp", label: "Outdoor grill area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-38.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-39.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-40.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-41.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-42.webp", label: "Outdoor area", span: 1 },
  { src: "/assets/img/images/Villa_Istria-43.webp", label: "View", span: 1 },
  { src: "/assets/img/images/Villa_Istria-44.webp", label: "View", span: 1 },
  { src: "/assets/img/images/Villa_Istria-46.webp", label: "Aerial view", span: 1 },
  { src: "/assets/img/images/Villa_Istria-48.webp", label: "View", span: 1 },
  { src: "/assets/img/images/Villa_Istria-49.webp", label: "Surroundings", span: 1 },
  { src: "/assets/img/images/Villa_Istria-50.webp", label: "Surroundings", span: 1 },
  { src: "/assets/img/images/award-2025.png", label: "Award 1", span: 1 },
  { src: "/assets/img/images/award-2026.png", label: "Award 1", span: 1 },
];
