name: Deploy to test
on:
  push:
    branches:
      - staging
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
        working-directory: villa-istria/

      - name: Build
        run: ls && npm run build
        working-directory: villa-istria/

      - name: Export
        run: npm run export
        working-directory: villa-istria/

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          folder: villa-istria/out
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
