name: Deploy to test
on:
  push:
    branches:
      - staging
jobs:
  deploy-to-test:
    name: Deploy to test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install
        working-directory: villa-istria/

      - name: Build
        run: yarn build
        working-directory: villa-istria/

      - name: Export
        run: yarn export
        working-directory: villa-istria/

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          local-dir: villa-istria/out/
          server-dir: test.villa-istria.hr/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
